// P17 — Stage-6 Process-Summary Typst document builder. SEPARATE from the paper's
// two-column IEEE template (typst-template.ts): this is a single-column report of the
// Stage-6 content ONLY (the AI Self-Reflection Report, the Collaboration Depth scores,
// and the Failure-Mode Audit Log). It never includes the paper body — the paper has its
// own PDF via /api/export-pdf. Compiled by /api/export-summary-pdf.

// A generic structured document the route compiles. The page assembles this from the
// already-rendered Stage-6 data so the server does no LLM work and trusts only plain text.
export interface SummaryDoc {
  title: string
  subtitle?: string
  sections: SummarySection[]
}

export interface SummarySection {
  heading: string
  // Plain-text paragraphs (each rendered as its own block).
  paragraphs?: string[]
  // Optional bullet list.
  bullets?: string[]
  // Optional simple table (header row + body rows). All cells are plain text.
  table?: { header: string[]; rows: string[][] }
}

// Escape text for Typst content mode (no math handling needed for a process report).
function escapeTypst(input: string): string {
  return input
    .replace(/\\/g, '\\\\')
    .replace(/#/g, '\\#')
    .replace(/\$/g, '\\$')
    .replace(/\*/g, '\\*')
    .replace(/_/g, '\\_')
    .replace(/\[/g, '\\[')
    .replace(/\]/g, '\\]')
    .replace(/@/g, '\\@')
    .replace(/</g, '\\<')
    .replace(/>/g, '\\>')
}

function renderTable(table: { header: string[]; rows: string[][] }): string {
  const cols = table.header.length
  const headerCells = table.header.map((h) => `[*${escapeTypst(h)}*]`).join(', ')
  const bodyCells = table.rows
    .map((row) => row.map((c) => `[${escapeTypst(c)}]`).join(', '))
    .join(',\n  ')
  return `#table(\n  columns: ${cols},\n  ${headerCells},\n  ${bodyCells}\n)`
}

function renderSection(section: SummarySection): string {
  const parts: string[] = [`== ${escapeTypst(section.heading)}`]
  if (section.paragraphs) {
    for (const p of section.paragraphs) {
      if (p.trim().length > 0) parts.push(escapeTypst(p))
    }
  }
  if (section.bullets && section.bullets.length > 0) {
    parts.push(section.bullets.map((b) => `- ${escapeTypst(b)}`).join('\n'))
  }
  if (section.table && section.table.rows.length > 0) {
    parts.push(renderTable(section.table))
  }
  return parts.join('\n\n')
}

export function buildSummaryTypstDocument(doc: SummaryDoc): string {
  const body = doc.sections.map(renderSection).join('\n\n')
  const subtitle = doc.subtitle ? `\n      #v(3pt)\n      ${escapeTypst(doc.subtitle)}` : ''
  return `// Generated by ARS Web Studio — Stage-6 Process Summary (single column).\n// Stage-6 content only; the paper body has its own PDF.\n#set page(paper: "a4", margin: (x: 20mm, y: 20mm))\n#set text(size: 10pt)\n#set par(justify: true, leading: 0.6em)\n#set heading(numbering: "1.")\n\n#align(center)[\n  #text(size: 16pt, weight: "bold")[${escapeTypst(doc.title)}]${subtitle}\n]\n\n#v(12pt)\n\n${body}\n`
}
