import type { PaperState } from '@/lib/types'
import { contentToMarkdown, paperAuthorsLine, startsWithHeading } from './content'

function escapeTypstText(input: string): string {
  const parts = input.split(/(\$\$[\s\S]*?\$\$|\$[^$\n]+\$)/g)
  return parts.map((part) => {
    if (part.startsWith('$$')) return `$ ${part.slice(2, -2).trim()} $`
    if (part.startsWith('$')) return `$ ${part.slice(1, -1).trim()} $`
    return part
      .replace(/\\/g, '\\')
      .replace(/#/g, '\\#')
      .replace(/\*/g, '\\*')
      .replace(/_/g, '\\_')
      .replace(/\[/g, '\\[')
      .replace(/\]/g, '\\]')
  }).join('')
}

function removeDuplicateHeading(markdown: string, heading: string): string {
  const lines = markdown.trim().split('\n')
  if (startsWithHeading(markdown, heading)) lines.shift()
  return lines.join('\n').trim()
}

function markdownToTypst(markdown: string): string {
  return markdown
    .split('\n')
    .map((rawLine) => {
      const line = rawLine.trim()
      if (!line) return ''
      const heading = line.match(/^(#{2,4})\s+(.+)$/)
      if (heading) return `${'='.repeat(Math.min(heading[1].length, 3))} ${escapeTypstText(heading[2])}`
      const bullet = line.match(/^[-*]\s+(.+)$/)
      if (bullet) return `- ${escapeTypstText(bullet[1])}`
      const numbered = line.match(/^\d+[.)]\s+(.+)$/)
      if (numbered) return `+ ${escapeTypstText(numbered[1])}`
      return escapeTypstText(line)
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

export function buildTypstDocument(paper: PaperState): string {
  const authors = paperAuthorsLine(paper)
  const affiliations = paper.config.authors
    .map((author) => author.affiliation)
    .filter(Boolean)
    .join('; ')

  const sections = paper.sections.map((section) => {
    const markdown = removeDuplicateHeading(contentToMarkdown(section.content), section.heading)
    return [`= ${escapeTypstText(section.heading)}`, markdownToTypst(markdown)].filter(Boolean).join('\n\n')
  })

  return `// Generated by ARS Web Studio.\n// Local IEEE-like two-column Typst template; no runtime network fetches.\n#set page(\n  paper: "a4",\n  margin: (x: 17mm, y: 18mm),\n  columns: 2,\n)\n#set text(size: 9pt)\n#set par(justify: true, leading: 0.55em)\n#set heading(numbering: "1.")\n\n#place(top + center, float: false)[\n  #block(width: 100%)[\n    #align(center)[\n      #text(size: 17pt, weight: "bold")[${escapeTypstText(paper.config.topic)}]\\\n      #v(4pt)\n      ${escapeTypstText(authors)}\\\n      ${affiliations ? escapeTypstText(affiliations) : ''}\n    ]\n  ]\n]\n\n#v(10pt)\n\n${sections.join('\n\n')}\n`
}
